#!/bin/sh
set -euf -o pipefail

##
# Set trackpoint speed and sensitivity to fastest settings.
#
# This also turns on the trackpoint option for press-to-select.
#
# Example:
#
#     $ thinkpad-trackpoint-set-speed-and-sensitivity-to-fastest
#     ... now you have a fast trackpoint ...
#
# See also:
#
#     thinkpad-trackpoint-find-device-file-for-sensitivity
#     thinkpad-trackpoint-find-device-file-for-speed
#     thinkpad-trackpoint-find-path-id
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

for i in 1 2 3
do
 dir=/sys/devices/platform/i8042/serio1/serio$i
 if [ -d $dir ]; then
  echo -n 255 > $dir/speed
  echo -n 255 > $dir/sensitivity
  echo -n 1 > $dir/press_to_select
 fi
done
