#!/bin/sh
set -euf -o pipefail

##
# Find a ThinkPad computer's TrackPoint Path ID.
#
# From http://www.thinkwiki.org/wiki/How_to_configure_the_TrackPoint
#
# See also http://sourceforge.net/projects/tpctl/
#
# Example:
#
#     ID_PATH=platform-i8042-serio-2
#
# See also:
#
#     thinkpad-trackpoint-find-device-file-for-sensitivity
#     thinkpad-trackpoint-find-device-file-for-speed
#     thinkpad-trackpoint-set-speed-and-sensitivity-to-fastest
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

/lib/udev/path_id $(find /sys/devices/platform/i8042 -name name | xargs grep -Fl TrackPoint | sed 's/\/sys\(.*\)\/name/\1/')
